### PR TITLE
Enhancements to Course Redirection in CourseCards Component

### PR DESCRIPTION
**Pull request by sanyadureja**
This pull request introduces key enhancements to the CourseCards component, focusing on improving user navigation and accessibility to educational content. The primary changes include the update of course links for better redirection and fixes in the Card.jsx component to ensure proper functionality.

Changes Made
- Updated Course Links: The links for several course cards have been revised to direct users to the corresponding YouTube playlists or the creator's channels. This ensures that users have quick and easy access to quality educational materials.

- Card Component Functionality: Enhanced the Card component in Card.jsx to ensure that clicking on any course card will properly open the designated link in a new tab. This improves user experience by allowing seamless navigation to external content without leaving the current page. Implemented target="_blank" and rel="noopener noreferrer" in the anchor tags for security and performance benefits.

- Missing Links Notification:
I have identified two course cards that currently lack accessible YouTube links:
Go by Akash Thakur
Ruby by Bhavin Patel
It would be beneficial to add these links for completeness. If you could provide the relevant URLs or guidance on where to find them, it would enhance the resourcefulness of the course offerings.

Benefits of Changes
- Improved User Experience: The updated links and functional enhancements provide a smoother user experience, enabling quick access to course materials.
- Increased Engagement: By ensuring users can easily navigate to relevant content, we can foster higher engagement with the courses offered on this platform.

These enhancements are designed to elevate the overall functionality of the CourseCards component, ensuring that users receive the best possible educational resources. I appreciate your consideration of this pull request and look forward to any feedback you may have.

### CODE REVIEW

**Comment by sanyadureja** [comment]
@Shreyaa173  I've completed the task - fixed #58  issue by adding the new project. Looking forward to getting my PR accepted and the project merged. Please give your meaningful suggestions.

Thank you !!

**Comment by Shreyaa173** [comment]
Can you provide some demo video of what you have done??

**Comment by sanyadureja** [comment]
> Can you provide some demo video of what you have done??

Sure will send the video

**Comment by sanyadureja** [comment]
@Shreyaa173 Please check the demo video. 

This pull request introduces key enhancements to the CourseCards component, focusing on improving user navigation and accessibility to educational content. The primary changes include the update of course links for better redirection and fixes in the Card.jsx component to ensure proper functionality.


Uploading redirection-of-course-cards.mp4…

**Comment by sanyadureja** [comment]
@Shreyaa173 thank you

**Comment by sanyadureja** [comment]
@Shreyaa173 please assign all the labels here at the merged stage so that it can be updated on the leaderboard.

**Comment by sanyadureja** [comment]
> @Shreyaa173 please assign all the labels here at the merged stage so that it can be updated on the leaderboard and also get accepted by hacktoberfest.
> 
> Currently it's showing not accepted, please check.
> 
> Screenshot_20241012_142746_Chrome

@Shreyaa173 any update on this?

**Comment by sanyadureja** [comment]
@Shreyaa173 please do the needful, looking forward to your response.

**Comment by sanyadureja** [comment]
> @Shreyaa173 please assign all the labels here at the merged stage so that it can be updated on the leaderboard and also get accepted by hacktoberfest.
> 
> Currently it's showing not accepted, please check.
> 
> Screenshot_20241012_142746_Chrome

@sanjay-kv can you please help me with this

**Comment by sanyadureja** [comment]
> @Shreyaa173 please assign all the labels here at the merged stage so that it can be updated on the leaderboard and also get accepted by hacktoberfest.

> Currently it's showing not accepted, please check.
> 
> Screenshot_20241012_142746_Chrome

@sanjay-kv 
@Shreyaa173 I request you to please assign the labels.

**Review by sanjay-kv — COMMENTED** [review]
good

**Comment by sanyadureja** [comment]
> good

Thank you so much @sanyadureja.

**Pull request merged**
