### PR TITLE
Added a Responsive design to course section and added youtube channels links to the cards

### PR DESCRIPTION
**Pull request by shravya312**

### CODE REVIEW

**Comment by shravya312** [comment]
Hii @Shreyaa173  I have added almost all the youtube channel link did not find 4 youtube channel link
->Bhavin Patel-Ruby
->Prateek Narang-CSS
->Akash Thakur-go language
->Anurag Tiwari-PHP
Can u please share the other links I will update the same in the code with the new pr or same pr
Hi @Shreyaa173 can you add the labels gssoc-extd, hacktoberfest-accepted and level-2.

**Comment by Shreyaa173** [comment]
No worries I'll add them on my own

**Comment by Shreyaa173** [comment]
Can you show me the demo video of responsive design and the links opening??

**Comment by shravya312** [comment]
image
I guess some connection error

**Pull request merged**
