### PR TITLE
chatbot added ✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
the chatbot has been added , @Shreyaa173  im so sorry for the delay, please review this.
thank you.

https://github.com/user-attachments/assets/fb0d161d-160d-4283-bb00-f95c70cd9404

### CODE REVIEW

**Comment by Shreyaa173** [comment]
Great work

**Comment by Shreyaa173** [comment]
But it has some conflicts in merging can you check for that??

**Comment by T-Rahul-prabhu-38** [comment]
done👍

**Comment by T-Rahul-prabhu-38** [comment]
@Shreyaa173 there is a problem , i got confused with the repos and made a PR here and added a chatbot to this website.
but i never raised an issue here.
howevr since no one has raised that issue yet can i raise it and u assign me that .

**Pull request merged**
