### PR TITLE
Feat: Contact Us backend using nodemailer

### LINKED ISSUE #206: Add Nodemailer Functionality for "Contact Us" Section
**Description:**
We need to implement Nodemailer functionality to send emails when a user submits the "Contact Us" form. This feature will enable us to receive inquiries directly via email, enhancing our communication with users.

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes #206 #288  Adding the ContactUs functionality using Nodemailer:)
For explaination you can refer my prevoius PR #288 

@Shreyaa173  Please review:)
And make sure you have your working email and one time password (For generating you can use google) once you have this then any one can recieve  mail please check .env file otherwise you will not get any mail:)

Proof:) 

proof

https://github.com/user-attachments/assets/1fd2f59e-2984-460f-b25c-ef343a156458

### CODE REVIEW

**Comment by Shreyaa173** [comment]
Uploading Screen Recording 2024-10-23 220458.mp4…

It is very quick

**Comment by harshbhar0629** [comment]
It depends on your internet speed

**Comment by harshbhar0629** [comment]
I can't able to see your video

**Comment by harshbhar0629** [comment]
Please merge i also provide the working video and mail screenshot what i send and what i get

**Comment by Shreyaa173** [comment]
I guess now it is visible

**Comment by Shreyaa173** [comment]
image
It has some network issue

**Comment by harshbhar0629** [comment]
You edit . Env file or not.? Please enter you mail ID and one time  password

**Comment by harshbhar0629** [comment]
I can't share my personal ID and password

**Pull request merged**
