### PR TITLE
[enhancement]: Add Dark and light mode functionality

### LINKED ISSUE #187: [enhancement]: Add Dark and light mode functionality
Description:
It would be beneficial to add a toggle for Dark and Light mode in the application. This feature will improve user experience by allowing users to switch between themes based on their preferences or system settings. A Dark mode can help reduce eye strain, especially in low-light environments, while Light mode is preferred during the day or in bright settings.

Steps to Reproduce:
Navigate to the homepage of the application.
Look for a setting to toggle between Dark and Light modes.
Notice that there is no option to switch themes.
Expected Behavior:
There should be a toggle or switch available in the settings or user interface that allows users to change between Dark and Light modes. The application should adapt accordingly based on the selection.

Actual Behavior:
Currently, there is no functionality to toggle between Dark and Light modes, and the user is limited to one theme throughout the application.

### PR DESCRIPTION
**Pull request by faiz66388**
light mode:
image
Dark Mode:
image
Closes #187

### CODE REVIEW

**Comment by Shreyaa173** [comment]
image

Screenshot 2024-10-16 151558

Things are not visible

**Comment by faiz66388** [comment]
@Shreyaa173 Could you check if this work for you?

**Comment by faiz66388** [comment]
@Shreyaa173 Could you check if this work for you?

**Comment by Shreyaa173** [comment]
Nopes

**Comment by faiz66388** [comment]
@Shreyaa 173 Could you please clarify the requirements or the direction you'd like me to take with these changes?

**Comment by Shreyaa173** [comment]
Majorly you have to do work in the light theme. The color of website completely becomes light in the light theme and in the dark theme it can be as it as the actual website colors.

**Pull request closed without merging**
