### PR TITLE
implement google/apple login in sign up page >>>>

### PR DESCRIPTION
**Pull request by REHAN-18**
issue #332 
implement the google & apple Enhance the sign-up page with a modern, aesthetic UI by integrating Google and Apple login options.
before ---
Screenshot 2024-10-25 at 12 43 24 PM
after--
Screenshot 2024-10-25 at 12 51 50 PM

@Shreyaa173 pls merge asap!!!!

### CODE REVIEW

**Comment by Shreyaa173** [comment]
Aren't they functional??

**Comment by REHAN-18** [comment]
no

**Comment by Shreyaa173** [comment]
Can you implement backend in it?? If not then it's not needed

**Comment by REHAN-18** [comment]
ok I will do it >>>> give me level 3 label

**Comment by REHAN-18** [comment]
@Shreyaa173 done added backend for sign up !!! pls Give level 3 label !!

**Comment by Shreyaa173** [comment]
Deployment is failed. Please check

**Comment by REHAN-18** [comment]
@Shreyaa173 I have check everything is working fine but this is vercel deploying issue !!!

**Comment by REHAN-18** [comment]
@Shreyaa173 have you check ???

**Comment by REHAN-18** [comment]
@Shreyaa173 now resolve all the conflict pls see & merge it asap !!

**Comment by Shreyaa173** [comment]
It has deployment error so closing it

**Pull request closed without merging**
