### PR TITLE
Feat: Adding Login and Signup Functionality with Backend + Database

### LINKED ISSUE #162: Adding Signup and Login Feature
It seems that login and sign up functionality is lacking so I would like to contribute to it using React and connecting it with mongoDB

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes #162 Adding login and signup functionality with backend + database.

**Testing Video:)**

https://github.com/user-attachments/assets/d384b332-8c65-4236-870f-701a6e24d19c

**Database user resgiteration:)**

data

**Changes in file:)** 

**Folder Structure**
**BACKEND**
**Backend**: It contains the whole backend of login and signup functionality.
**Config**: It connect the node environment to the database with dbConnect() function.
**Controllers**: In controllers there is a auth.js which is related to the authentication with all validation and i also used hashing(Bcrypt package) for to secure the password and also used Json-Web-Token for validation of token. No same user can create an account on this platform via same email address.
Models: There is only one model which is User model contains ["Firstname", "Lastname", "Email", "Password", "image-url", "token"].
**.env file:** In this file there are 3 deafult value you can add or edit accordingly.
MONGODB_URL = mongodb://127.0.0.1:27017/ It req database url
JWT_SECRET = "MYSECRET" Select your token
PORT = 4000 Enter your port number

**Index.js:** There is basic setup of express and also used middlewares for parsing data.

**UI**
**Components/Auth** : There are 3 components are there Template.js LoginForm.js, SignupForm.js On the basis of condition I render Login and signupform respectively! There is simple setup for login and signup using tailwindCSS.
**SignupForm** : When user click on create account we call to backend for creating a user and also show toast for interactive UI.
**LoginForm :** When user click on Sign in we call to backend for checking this user exist or not and also hashed their password for matching this is same passsword or not.

**Reducer:** We combine all the reducer or slices which is used in login and signup functionality.
**Slices:** We create two slices 1. authSlice which mainly holds token and profileSlice contains the user data for future purpose like for creating a dashboard of user then data will be required so I secured all data for now!.
**Services/operations**: Inside operations there is one file authAPI which connects or call the backend from the client side and send response accordingly, There are 3 main functions are there LOGIN, SIGNUP, LOGOUT, In login and signup we take data from client side and make a call to apiConnector to pass the given data and show response accordingly!

**Services/apiConnector.js:** In this file it only recieve the given data from client side and return an axios instance with taking the method of call, data, url, headers, params

**Services/api.js:** In this file I'm mentioning the all routes of backend which is used in login and signup functionality!.

**App.js:** In App.js I'm creating a home page so every listing and everything lie on Home page and also create a route for login and signup.

Index.js: I just wrapped the App component in Provider of react-redux.

Now executable command is changed so Enter: **npm run dev** so that backend and frontend starts immediately! Please remeber the commands:) and also updates in readme.md file.

Please edit the path of BASE_URL when you merge code because now BASE_URL is for localhost:)

@Shreyaa173 Please review and merge with **level-3**. @Shreyaa173

### CODE REVIEW

**Comment by harshbhar0629** [comment]
@Shreyaa173 Please review my PR and merge it:)

**Comment by Shreyaa173** [comment]
It's good but it has some css issues 
image

**Comment by harshbhar0629** [comment]
Ok i will edit footer

**Comment by harshbhar0629** [comment]
@Shreyaa173 I edit both navbar and footer now you can see here and now you are thinking there is no commit then how he is updated because i have created a two pull request #288 here i commit all changes:)
**NOW UI:)** 

https://github.com/user-attachments/assets/a5777cbb-53fd-42d9-84fa-086926755fde

**Comment by harshbhar0629** [comment]
@Shreyaa173 Please review again:)

**Comment by harshbhar0629** [comment]
@Shreyaa173 Please review:)

**Comment by Shreyaa173** [comment]
Some issues in it. Deployment is failed. Can't merge it now

**Comment by harshbhar0629** [comment]
I will create PR again:)

**Pull request closed without merging**
