### PR TITLE
 Integrate Password Recovery Feature #318

### LINKED ISSUE #318: Integrate Password Recovery Feature
Screenshot 2024-10-15 022439
Screenshot 2024-10-15 024732
📝 Feature Description
Integrate a password recovery feature that allows users to securely reset their passwords through a verification process, improving user experience and security.

🔧 How Will This Enhance the App?
This feature will enable users who forget their passwords to regain access to their accounts quickly and securely, reducing frustration and improving user retention.

🎯 Use Cases
User Forget Password: A user who has forgotten their password can request a password reset link via email.
Account Recovery: Users can recover their accounts without contacting support, enhancing the overall user experience.
📦 Suggested Implementation
Implement a "Forgot Password?" link on the login page.
Create a form to collect the user’s email address.
Send a password reset link to the user’s email, including a secure token for verification.
Provide a form for the user to enter a new password once they click the reset link.
📸 Additional Context
This feature aligns with common security practices and is essential for maintaining user trust and account security.

Screenshots/Video:
Screenshot 2024-10-22 231335
Screenshot 2024-10-23 023051
Screenshot 2024-10-21 232232
Screenshot 2024-10-22 001505
Screenshot 2024-10-20 025545
Screenshot 2024-10-15 192639

https://github.com/user-attachments/assets/6d480472-3993-4c15-873e-ba10e80e71a2

https://github.com/user-attachments/assets/574ed3c6-4e23-4c36-b7be-9ca1e3c4c6af

### PR DESCRIPTION
**Pull request by saras-69**
Description
This pull request integrates the Password Recovery Feature, enabling users to securely recover their accounts in case they forget their passwords. The feature involves both front-end and back-end updates, ensuring a smooth and secure password reset process via email OTP verification.

Issue Number
Close #318

Key Changes
Password Recovery Page: Frontend implementation for the recovery page.
Form Validation: Implemented secure form validation for password reset.

Screenshots:

https://github.com/user-attachments/assets/0aba65b2-ea24-41e2-afcf-b0bfd96b0add

Screenshot 2024-10-23 183010

### CODE REVIEW

**Comment by Shreyaa173** [comment]
Can you please I guess I have edited something now the deployment is failed. I'm not able to understand the error. Can you check for it?

**Comment by saras-69** [comment]
> Can you please I guess I have edited something now the deployment is failed. I'm not able to understand the error. Can you check for it?

Sure

**Comment by saras-69** [comment]
Hey @Shreyaa173 Could you please review my PR when you have a moment?

**Comment by Shreyaa173** [comment]
Deployment is failed. Can't merge it now

**Comment by Shreyaa173** [comment]
Closing it

**Comment by saras-69** [comment]
> Deployment is failed. Can't merge it now
Hey @Shreyaa173, Could you please clarify the specific issue affecting the deployment? I'd like to better understand the challenge to help address it effectively.

**Comment by saras-69** [comment]
Or if possible, could I create a new PR to work on resolving the deployment issue? This way, I can make the necessary adjustments directly.

**Pull request closed without merging**
