### PR TITLE
Updated Complete Courses section and card preview, Implemented slider concept and fixed many minor bugs

### PR DESCRIPTION
**Pull request by coderrrx-Brijesh**
https://github.com/user-attachments/assets/1cd4b77b-d43d-4d4e-a478-23adb932350e

### CODE REVIEW

**Comment by Shreyaa173** [comment]
Did I assigned you this?? Which issue you solved??

**Comment by coderrrx-Brijesh** [comment]
> Did I assigned you this?? Which issue you solved??

Yes you assigned me, I have solved Issue #167. Please merge my code and check the video for  reference and check what new I have done.

**Comment by Shreyaa173** [comment]
I didn't like it. Can you do something else?

**Comment by coderrrx-Brijesh** [comment]
> I didn't like it. Can you do something else?

common yrr, it really took me whole day to think and implement  that design, I am waiting for my first pull request to be merged, I will be really glad if you can merge my pull request, later on you can assign anyone to redesign that section, or just merge my pull request, i will again redesign this as a new issue.

**Comment by Shreyaa173** [comment]
Sorry not possible

**Pull request closed without merging**
