### PR TITLE
I have added a projects section under courses and projects 

### PR DESCRIPTION
**Pull request by amrutha-m206**
Issue #221 
This section  is under courses and projects and has links to various projects for different langauges which helps the user to get hands on practical experience after learning from the courses. It also has a gradient feature .

image

### CODE REVIEW

**Comment by Shreyaa173** [comment]
Can you make it according to the theme??

**Comment by Shreyaa173** [comment]
I'm not able to see it in the deployment

**Comment by amrutha-m206** [comment]
image

i have made the changes

**Comment by amrutha-m206** [comment]
> I'm not able to see it in the deployment

image
it says authorization needed to deploy

**Comment by Shreyaa173** [comment]
Didn't you sync the repo as it is showing the previous UI of codebook on deployment not the latest one

**Comment by amrutha-m206** [comment]
> Didn't you sync the repo as it is showing the previous UI of codebook on deployment not the latest one

I took the latest one itself , started doing it today morning so whatever was there till then I took that

**Comment by Shreyaa173** [comment]
Even though I merged it I couldn't see any changes in the website. 

https://github.com/user-attachments/assets/3ac4b1a8-9139-4076-be87-ed7c379b4dab

**Comment by amrutha-m206** [comment]
> Even though I merged it I couldn't see any changes in the website.
> 
>  Screen.Recording.2024-10-27.231740.mp4

I guess that needs to be sorted from your side as I do not have the authorization to deploy , also I did download the latest code of code block and I don't see the latest ones(of others)  in the UI .

**Pull request merged**
