### PR TITLE
add search icon in explore course. #271

### PR DESCRIPTION
**Pull request by amanreddy77**
### PR Description: Add Search Icon to Search Bar #271

**Overview:**
This pull request enhances the user interface of the Courses component by adding a search icon inside the search bar. The icon improves usability by visually indicating the search functionality to users.

**Changes Made:**
- Integrated Font Awesome for icon support.
- Updated the `Courses` component to include a search icon within the search bar.
- Adjusted the CSS to correctly position the search icon on the input field's right side.

**Files Modified:**
- `Courses.js`: Updated to include the search icon.
- `styles.css`: Added CSS rules for positioning the search icon within the search bar.

**Screenshots:**
Screenshot 2024-10-19 at 00 55 39

**Testing:**
- Verified that the search icon is correctly displayed within the search bar.
- Confirmed that the search functionality (if implemented) works as expected.

**Next Steps:**
- Integrate search functionality to filter courses based on user input.

---

Feel free to customize this description further based on your project’s specifics!

### CODE REVIEW

**Comment by amanreddy77** [comment]
hi @Shreyaa173 I have added the search icon and enhanced the spacing of the search bar can you please merge my PR and check the updates

**Comment by Shreyaa173** [comment]
It has some conflicts. Please check for them

**Comment by amanreddy77** [comment]
ok now you can merge it

**Comment by amanreddy77** [comment]
@Shreyaa173  can you please merge My PR

**Comment by Shreyaa173** [comment]
Some issues in it. Deployment is failed. Can't merge it now

**Pull request closed without merging**
