### PR TITLE
Update App.css

### PR DESCRIPTION
**Pull request by TusharNaugain**
The hover button of the heading "Code your way to success" was not working so i fixed that.

i have fixed the UI of footer part chaneged the style of of contact us and the code of description.

added effects of the Symbols, and make it more smooth.

### CODE REVIEW

**Comment by Shreyaa173** [comment]
Can you provide a demo for what you have done?

**Comment by Shreyaa173** [comment]
no need to do that

**Comment by TusharNaugain** [comment]
> no need to do that
um.. you need that then i'll copy paste the screenshot of that, else if there is something you can assign that to me!

**Comment by Shreyaa173** [comment]
Not now

**Pull request closed without merging**
