### PR TITLE
added login and signup components with styling 

### PR DESCRIPTION
**Pull request by lakshmirajvagu**
Issue #102 Before there is no login and sign up form now i added login and sign up form with decent styling 

u can check out here @Shreyaa173 

https://github.com/user-attachments/assets/444dc78e-d160-408d-8c34-96aeeabb43fb

### CODE REVIEW

**Comment by lakshmirajvagu** [comment]
@Shreyaa173 ok will sign up and login are already headings I will change text color to white and align then

**Comment by lakshmirajvagu** [comment]
@Shreyaa173 see the diffrence i have aligned and changed the text colour now its all perfect 

https://github.com/user-attachments/assets/039ea2ea-04af-47b1-ac28-2433a97ee042

**Comment by Shreyaa173** [comment]
It's good. Also make the text color white for the home and login. And decrease the length of email and password input box like the length of button. and make the login heading a lil big and bold

**Comment by lakshmirajvagu** [comment]
@Shreyaa173 iam not able to work on this please check this and merge

**Comment by Shreyaa173** [comment]
Ohk

**Pull request merged**
