### PR TITLE
Added Email functionalty to the contact form   issue #128

### PR DESCRIPTION
**Pull request by AyushSharma72**
what i did :

set up whole backend and added an api using nodeamailer
connected the api with the contact form 

images:
Screenshot (269)

email:
Screenshot (270)

please add gssoc-ext and level2 before merge @Shreyaa173

### CODE REVIEW

**Comment by Shreyaa173** [comment]
It's showing error 
image

**Comment by AyushSharma72** [comment]
> It's showing error image

Check the error in network tab and tell me  @Shreyaa173

**Comment by Shreyaa173** [comment]
I'm not able to understand it

**Comment by AyushSharma72** [comment]
> I'm not able to understand it

Share screenshot

**Pull request merged**
