### PR TITLE
Added Docs Links and books links in the card only Issue no: #126

### PR DESCRIPTION
**Pull request by Kiran-Jadhav200**
### Pull Request: Add Documentation and Books Links to Card Component

**Issue Reference:** #126

#### Summary
This pull request addresses the enhancement request to include documentation and books links within the `Card` component. The links are conditionally rendered based on the availability of the respective props.

#### Changes Made
- Updated the `Card` component to include:
  - A link to documentation (`docsLink`).
  - A link to books (`bookslink`).
- Ensured that both links are only displayed when their respective props are provided and truthy.
-  Added Youtube link for Ruby course

#### Testing
- Verified that the links appear correctly when the props are passed.
- Checked that the links do not render when the props are absent or falsy.
- Conducted cross-browser testing to ensure consistent behavior.

#### Screenshots
image

#### Additional Notes
- Please review the CSS to ensure the links are styled appropriately across different themes.
- No breaking changes introduced.

### CODE REVIEW

**Comment by Shreyaa173** [comment]
Please make the css for them as the author and lessons text are done.

**Comment by Shreyaa173** [comment]
Also the books one is not visible and no need to add the youtube one as image is redirecting to youtube itself. 
image
Also the Course head is not visible till we won't hover over it.

**Comment by Kiran-Jadhav200** [comment]
OK I have completed it   see 
image

**Review by Kiran-Jadhav200 — COMMENTED** [review]
in css I have change the height of card and also remove hover effect so the course name is visible and added docs links and books link

**Comment by Shreyaa173** [comment]
image
Make the height of cards a bit small and change the font color and make sure docs and books are in different lines with some spacing

**Comment by Shreyaa173** [comment]
The color that is used in the author and lessons font also make sure that you have maintain the same css as of author and lessons

**Comment by Kiran-Jadhav200** [comment]
@Shreyaa173 is this Ok ?? can i merge now ??

image

**Comment by Kiran-Jadhav200** [comment]
@Shreyaa173 I have completed all the Task please check and please merge it

**Comment by Shreyaa173** [comment]
The cards??
image

**Comment by Shreyaa173** [comment]
Closing the PR as already done

**Pull request closed without merging**
