### PR TITLE
 update(navbar): enhance nav item hover and animation for a more engaging experience

### PR DESCRIPTION
**Pull request by biswajit-sarkar-007**
### PR Description for Issue #193

**Summary of Changes**:
- Implemented hover effects and animations for the logo to enhance user interaction.
- Added improved animations for the nav items, including a 3D rotation and underline effect on hover.
- Redesigned the navbar buttons, adding hover effects and animations to make them visually appealing and attention-grabbing.
  
**Enhancements**:
- **Logo**: Now features a hover effect with smooth transitions and scaling for better engagement.
- **Nav Items**: Added interactive underline animations, color transitions, and 3D hover effects to make the navigation more dynamic.
- **Buttons**: Redesigned styles with hover animations, transforming them into more prominent, visually appealing components.

**Expected Behavior**:
- Improved user experience with more interactive and engaging navbar elements, including the logo, nav items, and buttons.

**Final Output**:

https://github.com/user-attachments/assets/b06c73b2-0f35-4716-af81-c4fd5ad37bd0

### CODE REVIEW

**Comment by Shreyaa173** [comment]
Didn't like the interface make the changes in the original one

**Comment by biswajit-sarkar-007** [comment]
@Shreyaa173, is there any problem regarding this PR?

**Comment by biswajit-sarkar-007** [comment]
@Shreyaa173, is there any issue with this PR?

**Comment by Shreyaa173** [comment]
Yes, it has some conflicts in merging. Please resolve them

**Comment by Shreyaa173** [comment]
Also, I didn't like the interface so closing it

**Comment by biswajit-sarkar-007** [comment]
okay

**Pull request closed without merging**
