### PR TITLE
Feat: ContactUs Functionality using Nodemailer

### LINKED ISSUE #206: Add Nodemailer Functionality for "Contact Us" Section
**Description:**
We need to implement Nodemailer functionality to send emails when a user submits the "Contact Us" form. This feature will enable us to receive inquiries directly via email, enhancing our communication with users.

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes #206 Adding the ContactUs functionality using Nodemailer:)

Test Functionality: )

https://github.com/user-attachments/assets/11efb2ef-3492-4593-9013-232de405fec0

.ENV FILE
(MAIL_PASS) You have to generate one time password by google and put it into .env file please don't share to anyone.

envFile

When we are submit our ContactUs form then it call to backend api using axios then it fetch data from backend and show corresponding output.

contactUsUI

Backend "/contact" will recieve the call and call to mail sender by passing the data

backendContact

Here is the core logic of nodemailer it creates transporter using your personal info and then send mail.

nodemailer

Template of recieving mail:)

template

@Shreyaa173 Please review it and merge with labels, @Shreyaa173

### CODE REVIEW

**Comment by harshbhar0629** [comment]
@Shreyaa173 Please assign level-3 it required alot of time and alot of code is there:)

**Comment by Shreyaa173** [comment]
Yeah I'll assign you level 3 but there is so many styling issues in it 
image
Positioning of items in the navbar

Screenshot 2024-10-19 211507
Screenshot 2024-10-19 211515
 logo in footer

**Comment by harshbhar0629** [comment]
I think this is because of importing tailwindCss

**Comment by harshbhar0629** [comment]
I will edit and again make a home page video and send to you @Shreyaa173 :)

**Comment by harshbhar0629** [comment]
@Shreyaa173 Please review and merge it i only edit css property, please assign level-3.
NOW UI:) 


https://github.com/user-attachments/assets/2a4d2709-295d-4eb9-8794-a4d93d1d0ca3

**Comment by Shreyaa173** [comment]
It has some conflicts can you check for these??

**Comment by harshbhar0629** [comment]
@Shreyaa173 Everything fine now:)

**Comment by harshbhar0629** [comment]
@Shreyaa173 Please review:)

**Comment by harshbhar0629** [comment]
Will you review my PR....??????

**Comment by Shreyaa173** [comment]
There is some issues in it the deployment is failed.

**Comment by harshbhar0629** [comment]
@Shreyaa173 I will create PR again:)

**Pull request closed without merging**
